version: '3.4'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
  gotrader:
    build:
      context: .
      dockerfile: Dockerfile
      target: run
