# User id to use API (required)
userid: "xxxxxxxxxxxxxxxxx"

# Password/Secret key to use API (required)
secret: "xxxxxxxxxxxxxxx"

# API endpoint/url. Aways use HTTPS! (required)
endpoint: "https://testnet.bitmex.com"

# Amount of asset for trade. Only integers (required)
hand: 3

# Asset to trade (required)
asset: "XBTUSD"

# Cadle time (minutes) (required)
candle: 30

# threshold to trigger the rule (required)
threshold: 3

# Profit percentage to close a position (required)
profit: 0.60

# Leverage value. Set a number between 0.01 and 100. 
# Send 0 to enable cross margin. (required) 
leverage: "0.1"

# Enable matrix (true/false) (required)
matrixuse: false

# Matrix API KEY
matrix_key: "!xxxxxxx:matrix.org"

# Matrix API URL
matrixurl: "https://matrix.org/"

# Matrix channel
matrixchannel: "@xxxxxxxx"
