# User id to use API (required)
userid: "xxxxxxxxxxxxxxxxx"

# Password to use API (required)
secret: "xxxxxxxxxxxxxxx"

# API endpoint/url. Aways use HTTPS! (required)
endpoint: https://testnet.bitmex.com

# Percentage to use on trade from total wallet value (required)
hand: 3

# Asset to trade (required)
asset: XBTUSD

# Cadle time (minutes)
candle: 30

# threshold to trigger the rule
threshold: 3

# Profit percentage to close a position
profit: 0.60

# How many depth orders
depth: 30

# Leverage value. Set a number between 0.01 and 100. 
# Send 0 to enable cross margin.
leverage: 0.1

# Telegram API KEY
telegram_key: "xxxxxxxxxxxxxxx"

# Telegram API URL
telegramurl: "https://api.telegram.org/"

# Telegram channel
telegramchannel: "@xxxxxxxx"